name: kroty
description: A professional task manager built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  sqflite: ^2.0.0+4  # أو room إذا كنت تفضل استخدامه
  google_ml_kit: ^0.6.0

flutter:
  uses-material-design: true
